systemDictionary = {
    "Home adapter settings": {"en": "Home adapter settings", "de": "Home Adapter-Einstellungen", "ru": "Настройки драйвера Home"},
    "Name":                  {"en": "Name",                  "de": "Name",                       "ru": "Имя"},
    "Group":                 {"en": "Group",                 "de": "Gruppe",                     "ru": "Группа"},
    "ID":                    {"en": "ID",                    "de": "ID",                         "ru": "ID"},
    "Role":                  {"en": "Role",                  "de": "Rolle",                      "ru": "Роль"},
    "Room":                  {"en": "Room",                  "de": "Raum",                       "ru": "Комната"},
    "Function":              {"en": "Function",              "de": "Funktion",                   "ru": "Функция"},
    "Binds":                 {"en": "Binds",                 "de": "Bindet",                     "ru": "Связать"},
    "Add device: ":          {"en": "Add device: ",          "de": "Add device: ",               "ru": "Добавить устройство: "},
    "Filter: ":              {"en": "Filter: ",              "de": "Filter: ",                   "ru": "Фильтр: "},
    "state":                 {"en": "state",                 "de": "state",                      "ru": "state"},
    "switch":                {"en": "switch",                "de": "switch",                     "ru": "switch"},
    "value":                 {"en": "value",                 "de": "value",                      "ru": "value"},
    "blinds":                {"en": "blinds",                "de": "blinds",                     "ru": "blinds"},
    "temperature":           {"en": "temperature",           "de": "temperature",                "ru": "temperature"},
    "humidity":              {"en": "humidity",              "de": "humidity",                   "ru": "humidity"},
    "indicator":             {"en": "indicator",             "de": "indicator",                  "ru": "indicator"},
    "counter":               {"en": "counter",               "de": "counter",                    "ru": "counter"},
    "Select ID":             {"en": "Select ID",             "de": "ID Auswählen",               "ru": "Выбрать ID"},
    "Select":                {"en": "Select",                "de": "Auswählen",                  "ru": "Выбрать"},
    "Cancel":                {"en": "Cancel",                "de": "Abbrechen",                  "ru": "Отмена"},
    "All":                   {"en": "All",                   "de": "Alle",                       "ru": "все"},
    "Select all":            {"en": "Select all",            "de": "Alle auswählen",             "ru": "Выбрать все видимые"},
    "Deselect all":          {"en": "Deselect all",          "de": "Auswahl aufheben",           "ru": "Убрать выделение"},
    "Invert selection":      {"en": "Invert selection",      "de": "Selektierung invertieren",   "ru": "Инвертировать выделение"},
    "Value":                 {"en": "Value",                 "de": "Wert",                       "ru": "Значение"},
    "From":                  {"en": "From: ",                "de": "Von",                        "ru": "От"},
    "Last changed":          {"en": "Last changed",          "de": "Letzte Änderung",            "ru": "Изменён"},
    "Time stamp":            {"en": "Time stamp",            "de": "Zeitstempel",                "ru": "Время"},
    "Acknowledged":          {"en": "Acknowledged",          "de": "Bestätigt",                  "ru": "Подтверждён"},
    "Processing...":         {"en": "Processing...",         "de": "Bearbeite...",               "ru": "Обработка..."},
    "Temporarily, to copy the bind variables: ": {
        "en": "Temporarily, to copy the bind variables: ",
        "de": "Vorübergehend zum Kopieren von Bind-Variablen: ",
        "ru": "Временно, для копирования связываемых переменных: "
    },
    "on save adapter restarts with new config immediately": {
        "en": "On save adapter restarts with new config immediately.",
        "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.",
        "ru": "Сразу после сохранения настроек драйвер перезапуститься с новыми значениями."
    }
};
